<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TweetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * Paginate tweets.
     *
     * @param int $page
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function getTweets($page, $user, $limit)
    {
        $query = $this->createQueryBuilder('t')
                ->where('t.user = :user')
                ->setParameter('user', $user)
                ->orderBy('t.created_at', 'DESC')
                ->getQuery();

        $paginator = $this->paginate($query, $page, $limit);

        return $paginator;
    }

    /**
     * Helper paginate method.
     *
     * @param Doctrine\ORM\Query $query
     * @param int                $page  Current page (defaults to 1)
     * @param int                $limit The total number per page (defaults to 5)
     *
     * @return \Doctrine\ORM\Tools\Pagination\Paginator
     */
    public function paginate($query, $page = 1, $limit)
    {
        $paginator = new Paginator($query);

        $paginator->getQuery()
            ->setFirstResult($limit * ($page - 1)) // Offset
            ->setMaxResults($limit); // Limit

        return $paginator;
    }

}
